CREATE TABLE DATOS_GENERALES (
    ID_PREGUNTA SERIAL PRIMARY KEY,  -- SERIAL se convierte en un tipo entero con autoincremento
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    TEL1 VARCHAR(15),
    TEL2 VARCHAR(15),
    CORREO VARCHAR(50),
    DIRECCION VARCHAR(50),
    EDAD INT,
    DPI VARCHAR(50),
    ESTADO_CIVIL VARCHAR(30),
    GENERO CHAR(1),
    ID_RECLUTAMIENTO INT,  -- Asegúrate de incluir la columna ID_RECLUTAMIENTO
    FOREIGN KEY (ID_RECLUTAMIENTO) REFERENCES RECLUTAMIENTO(ID_RECLUTAMIENTO)  -- Establece la clave foránea
);

CREATE TABLE CATEGORIA (
    ID_PREGUNTA VARCHAR(5) PRIMARY KEY,
    DESCRIPCION VARCHAR(150)
);

CREATE TABLE RECLUTAMIENTO (
    ID_RECLUTAMIENTO SERIAL PRIMARY KEY,
    ID_CATEGORIA INT,
    DESCRIPCION VARCHAR(250),
    DISPONIBLE BOOLEAN,
    FECHA_CREACION DATE,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(25) PRIMARY KEY,
    PASSWORD VARCHAR(25)
);

CREATE TABLE RESPUESTAS_LIMPIEZA (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    ID_DATOS_GENERALES INT,  -- Cambiar a INT
    GRADO_ACADEMICO VARCHAR(100),
    ANOS_EXPERIENCIA INT,
    DISPOSICION_HORARIOS BOOLEAN,
    MOTIVO_RENUNCIA VARCHAR(250),
    HURTO BOOLEAN,
    MANEJO_PRESUPUESTO TEXT,
    PERMISO_TELEFONO BOOLEAN,
    ENCUENTRO_DINERO BOOLEAN,
    REVISAR_TAREA BOOLEAN,
    ENCUENTRO_OBJETO VARCHAR(250),
    ID_CATEGORIA INT,  -- Nueva columna
    FOREIGN KEY (ID_DATOS_GENERALES) REFERENCES DATOS_GENERALES(ID_PREGUNTA),
);

CREATE TABLE RESPUESTAS_SEGURIDAD (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    ID_DATOS_GENERALES INT,  -- Cambiar a INT
    GRADO_ACADEMICO VARCHAR(100),
    ANIOS_EXPERIENCIA INT,
    DISPONIBILIDAD_ROTATIVOS BOOLEAN,
    MOTIVO_RENUNCIA_DESPIDO TEXT,
    ANTECEDENTES BOOLEAN,
    EXPLICACION_ANTECEDENTES TEXT,
    DETENCIONES BOOLEAN,
    EXPLICACION_DETENCIONES TEXT,
    LICENCIA_ARMA BOOLEAN,
    TIPO_LICENCIA VARCHAR(50),
    FUNCIONES_SEGURIDAD TEXT,
    ID_CATEGORIA INT,  -- Nueva columna
    FOREIGN KEY (ID_DATOS_GENERALES) REFERENCES DATOS_GENERALES(ID_PREGUNTA),
);

CREATE TABLE RESPUESTAS_ADMINISTRACION (
    ID_RESPUESTA SERIAL PRIMARY KEY,
    ID_DATOS_GENERALES INT,  
    GRADO_ACADEMICO VARCHAR(50),
    ANIOS_EXPERIENCIA VARCHAR(20),
    DISPONIBILIDAD_ROTATIVOS BOOLEAN,
    MOTIVO_RENUNCIA VARCHAR(100),
    ACTIVIDADES_ANTIGUO_TRABAJO VARCHAR(100),
    EQUIPOS_OFICINA_PUEDE_USAR VARCHAR(100),
    EQUIPOS_OFICINA_NO_PUEDE_USAR VARCHAR(100),
    ID_CATEGORIA INT,  -- Nueva columna
    FOREIGN KEY (ID_DATOS_GENERALES) REFERENCES DATOS_GENERALES(ID_PREGUNTA),
);

ALTER TABLE USUARIO
ADD COLUMN ROL VARCHAR(10) DEFAULT 'usuario';

UPDATE USUARIO
SET ROL = 'admin'
WHERE ID_USUARIO = 'Lucia';